### ISSUE TITLE
Замечания к работе №2

### ISSUE THREAD

**Issue by FlashAnton** [grrachevva/TYY-111#2]
Здравствуйте!

Сделайте, пожалуйста, единообразно. В этом невозможно разобраться.
![image](https://github.com/grrachevva/TYY-111/assets/95698986/eb4eab5e-4f25-41e2-bca2-7ea10398d040)

Простите, Вы как потом собираетесь это печатать?
Зачем белое на чёрном? Я не понимаю смысла такого расточительства расходных материалов.
![image](https://github.com/grrachevva/TYY-111/assets/95698986/4b26018d-2649-4148-b22e-4aa2d87d8a8c)

**Comment by grrachevva** [comment]
Антон Игоревич,добрый вечер! Начинаю печатать отчеты, на них написано "К защите". Подскажите пожалуйста, могу ли я начинать печать, если у меня работа защищена,но не исправлено написание?

**Comment by FlashAnton** [comment]
**Работа защищена во время аудиторного занятия**
