### ISSUE TITLE
К 6 работе

### ISSUE THREAD

**Issue by grrachevva** [grrachevva/TYY-111#7]
Антон Игоревич, добрый вечер! Отправила Вам задание №6.

**Comment by FlashAnton** [comment]
Здравствуйте!

Укажите, пожалуйста, когда была выполнена работа:
![image](https://github.com/grrachevva/TYY-111/assets/95698986/21f6357b-5be1-4483-a550-52bad025e0a2)

Считаю, что график у Вас не получился. Вам не нужна такая точность его расчёта.
Особенности графика по такому виду не прослеживаются:
![image](https://github.com/grrachevva/TYY-111/assets/95698986/f1c237c6-7b1f-42ba-9701-b0c53ec27aa7)

Форматирование кода не сохранилось:
![image](https://github.com/grrachevva/TYY-111/assets/95698986/e774fabb-2362-44f9-a0f8-40ab3edb55c1)

Читать такой результат тестирования очень сложно.
Выполните ограничение формата по выводу до трёх знаков после запятой максимум.
Более высокая точность расчётов не требуется.

![image](https://github.com/grrachevva/TYY-111/assets/95698986/753d5551-fa80-4403-b907-4ced7c95f330)

Просто попробуйте пример с отрицательным значением k. Вероятно, расчёт такого тестового примера не пройдёт.
С этим потребуется что-то сделать. Вам следует внимательнее посмотреть на косвенные ограничения.
![image](https://github.com/grrachevva/TYY-111/assets/95698986/9415fbf6-f1ce-4e59-ad3f-90a6a672a02b)

**Comment by grrachevva** [comment]
Антон Игоревич, добрый вечер! Я бы хотела у вас уточнить по работе. Я поняла что вы имеете в виду, на счёт того что k может быть отрицательным, только тогда когда а нечётно или также отрицательно. Но, я не понимаю как это реализовать. Спасибо.

**Comment by FlashAnton** [comment]
Добрый вечер.

Отрицательные k нужно отсечь на этапе ввода данных пользователем.
Контроль вне цикла должен быть в разы проще в составлении, чем внутри цикла.
Помните, что этот контроль актуален только при целых значениях (1/a).
Такое возможно, например:
![image](https://github.com/grrachevva/TYY-111/assets/95698986/54d739de-818c-4a51-9fd0-91dfaee78753)
Но могут возникать длинные вещественные хвосты при таком делении, поэтому судить о целом результате
можно в случаях, когда дробная часть результата по модулю меньше epsilon.

**Дробная часть числа = Само число - Целая часть числа без округления.**

Для взятия целой части числа без округления есть стандартная функция, то есть это не Round, не Ceiling, не Floor.
Что-то другое.

**Comment by grrachevva** [comment]
Антон Игоревич, добрый вечер! Недочеты устранила.

**Comment by FlashAnton** [comment]
Честно признаюсь - не вижу. Не вижу того, про что Вам выше расписал.
Ещё и графики куда-то пропали. Графики к тестовым примерам из постановки задачи никто не отменял.
Верните их, пожалуйста. Только в приличном виде. Где функция определена - есть точки, где не определена - нет точек.
Можно в MathCAD, можно в Excel - это как хотите.

**Comment by grrachevva** [comment]
Исправила отчет

**Comment by FlashAnton** [comment]
Теперь похоже на правду. Тестовый пример, конечно, всей особенности ситуации с k не раскрывает, но, по крайней мере, необходимая часть уже появилась.

**Зачтено**
