### ISSUE TITLE
К работе № 7 

### ISSUE THREAD

**Issue by grrachevva** [grrachevva/TYY-111#8]
Антон Игоревич, добрый вечер! Отправила Вам работу №7.

**Comment by FlashAnton** [comment]
Здравствуйте.

Вы забыли выполнить ассигнацию в этом Issue, потому далеко не сразу заметил наличие работы.
Зачту. Об особенностях ряда Вы подумали и выглядит работа прилично.
Вы зря некоторые связи протаскивали через лист транзитом. Это делать не требуется, но это не
является ошибкой.

**Зачтено**
