### ISSUE TITLE
К работе №8

### ISSUE THREAD

**Issue by grrachevva** [grrachevva/TYY-111#9]

**Comment by grrachevva** [comment]
Антон Игоревич, добрый день! Отправила Вам задание №8.

**Comment by grrachevva** [comment]
Добрый день! Посмотрите пожалуйста работу номер 8

**Comment by FlashAnton** [comment]
Здравствуйте.

Если решение не предполагает разветвления, то принимать решение не нужно и блок лишний?
![image](https://github.com/grrachevva/TYY-111/assets/95698986/c881dc16-5f4c-4527-9316-1e20a614fae2)
Аналогичный вопрос ко всем последующим блокам принятия решения на схеме.

В случае несоответствия размеров фрагментов схем, правда, следует перенести на другую страницу.
![image](https://github.com/grrachevva/TYY-111/assets/95698986/f061fb51-ab8d-46d4-9f4f-758d0c9007a1)

Новый массив вижу в тестовых примерах. А исходный? 
![image](https://github.com/grrachevva/TYY-111/assets/95698986/36ee7bea-ec5d-4456-90dd-1db33d9bdbee)

**Comment by FlashAnton** [comment]
Здравствуйте.

С выполненными правками согласен.

**Зачтено.**
